### ISSUE TITLE
Exporting Profiles/No install

### ISSUE THREAD

**Issue by TheRowdy** [Dijji/FileMeta#40]
Hi, is there any easy way to export custom profiles and re-import them?
If it isn't already possible, I believe a Cmd utility would be prefered.

In the same line of thoughts, is it possible to make file-meta install free?
Obviously, the software would still make registry edits/copy its files somewhere, but wouldn't require the user to go through the install setup(or how could I setup the source code to do so?)

**Comment by Dijji** [comment]
Right now, there is no way to export custom profiles and re-import them. However, the only storage used is in the registry, so it would be possible to extract the relevant registry keys and save them in a .reg file so that they could be applied on the same or another machine. It is a good feature idea though, I’ll add it to the list. Presumably, it would be good to have not just the profile definitions but the extensions to which they were applied preserved.

Install free is a bit trickier. If you look at what setup does (in Product.wxs), there are several COM registrations required. These could be done, however, when the Association Manager started, though I’m not clear how they would be removed on deletion. More difficult is the required installation of the right version of the C++ runtime, which as far as I know itself is only available as an installation. Another minor issue is the creation and removal of start-up menu entries. A possibility would be the use of the Windows 10 app packaging, but I doubt that’s what you’re trying to get to.

What requirements prompt your questions?

Dijji

**Comment by TheRowdy** [comment]
I would love to distribute your software as part of my suite(which I would share between my friends and myself)

**Comment by Dijji** [comment]
You can copy custom profiles from one machine to another. On a machine with the profiles setup as desired, all the definitions can be found at "\Users<Username>\AppData\Roaming\FileMeta\SavedState.xml". You can then take this file and use it with the command line tool FileMetaAssoc.exe to set up profiles on another machine, or for another user on the same machine. For example:

`FileMetaAssoc.exe -a -p=.bmp -d="D:\Configs\SavedState.xml" .bmp`

This is all described in the documentation.

Thinking more about installation, the sticking point that means you have to do run some sort of installation is the need to install the Visual C++ runtime. I can’t think of any simple way around it. Given this requirement, it is probably easier to take your code and add it to the File Meta installation to create a new installation of your own (the File Meta licence covers the creation of such derived works). This does present you with the learning curve needed to understand WIX, but that is not too horrible. You could also extend it to include setting up all the required profiles and file associations in the same set up.

Dijji
