### ISSUE TITLE
save/update with Notepad++ erase metadata

### ISSUE THREAD

**Issue by David-Dlps** [Dijji/FileMeta#86]
Hi,
When I save a TXT file with (Ms) notepad metadata is preserved.
When I do it with Notepad++ metadata is lost, any idea?

**Comment by Dijji** [comment]
To quote the readme: "Also, if your files are still being edited, then you need to check that associated metadata is preserved on save. Some file editors, rather than update the file in place, save updates using a write-new-file, delete-original-file, rename-new-to-original strategy that loses any metadata held in the annex to the original file. "

Notepad is known to work in a friendly way. It looks like Notepad++ is one of those applications that does not respect NTFS metadata. The issue does seem to be more common with third-party applications.

Dijji

**Comment by David-Dlps** [comment]
Totally true, I have already checked also with FoxItPDF and also metadata is lost. 
It seems I need to create a batch to "backup" my metadata on regular basis.
I am using FileMeta to catalogue only, it means, after add the right TAGs and Ranking I dont need anymore to modify the properties.

Note. I will also create a batch for listing all metadata, this is useful to know how I am "classifying" my files. For example

File1.txt ............. Tags: MyProp1:valueABc1
File2.txt ............. Tags: MyProp1:valueAB1
File3.txt ............. Tags: MyProp1:valueABC1
File3.txt ............. Tags: MyProp1:valueABC

then I will get a list of : valueABc1, valueAB1, valueABC1,valueABC 

and then realize that I am an Idiot and made some typo and only value needed was "MyProp1:valueABC1" for example.
