### ISSUE TITLE
Error when adding a Tag

### ISSUE THREAD

**Issue by andrewdci03** [Dijji/FileMeta#92]
Using the association manager, I added the handler for .txt's and .pdf's, when trying to add tags to these I receive the following error:

"An unexpected error is keeping you from applying properties to the file. If you continue to recieve this error, you can use the error code to search for help with this problem.

Error 0x80004005: Unspecified error

**Comment by Dijji** [comment]
This error code is the gloriously unspecific E_FAIL. Its appearance when first setting property values having used the Association Manager goes all way back to 2013, and the very first versions of File Meta.

It is linked to the caching done by Windows Explorer, which is why the Association Manager offers to restart it on exit if you have made changes. This has mostly eradicated the problem, but it does not always work. Try rebooting the system instead and see if the problem recurs.

Dijji
