### ISSUE TITLE
I love this app, but search a little slow. Dijji has solved!

### ISSUE THREAD

**Issue by warrentdo** [Dijji/FileMeta#96]
Hello, Although I really love this app im finding that search a little slow.
I have several computers attached to a server.
I have your software on everything so i can add tags from anything to be seen on everything.
This is fantastic!!!!!
Although I can search withing directories with no problems im finding a simple search tag:warren is very slow.
I do have quite a large amount of files.
Is there anything i can do to speed up the searching?
Regards,
Warren.

**Comment by Dijji** [comment]
Rapid search is search where the results are being provided by the Indexing Server. You can go to Indexing Options in Settings and configure which directories are indexed. The idea is to have all the directories that you need, but no extras, and then search only in indexed folders, so that no linear trawling is required.

The way in which a property is indexed is controlled by its configuration. In the case of tags, this means the configuration of the System.Keywords property. This comes preconfigured, and it is set as described here: https://docs.microsoft.com/en-us/windows/win32/properties/props-system-keywords

The inInvertedIndex means that each word in each tag is used as a key, as well as each tag as a whole. Being a Column makes it queryable. Interrogating the property description on my system also reveals that its index is held on disk, which is the fastest form.
 
So I would say that the property set up is about ideal. All that you can really do to control speed is to set up Indexing Options carefully, and search in indexed folders.

Dijji

**Comment by warrentdo** [comment]
Thank you again for both a fantastic program, and your helpful advice.
Regards,
Warren.

**Comment by warrentdo** [comment]
Hello Dijji,
I have adjusted the indexing server and now all the devices are finding files with ease.
Thank you again for your help.
Best regards,
Warren.
